[package]
name = "vikeypass"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26.0"
rand = "0.8.5"
tui = "0.19.0"
thiserror = "1.0"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4.23"
arboard = "3.2.0"
keyring = "2.0.1"
magic-crypt = "3.1.12"
